# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading) Familarizing my self to Pytorch

##### Practicing Documentation Code

Here I am going to briefly practice doc coding from documentation on torch.Tensor

In [2]:
# Practicing documentation code
import torch
torch.zeros([2,4],dtype = torch.int32)

# cuda0 = torch.device('cuda:0')
# torch.ones([2,4],dtype = torch.float64,device = cuda0)



tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [3]:
# Contents of a tensor can be accessed and modified using Python's indexing and slicing notation
x = torch.tensor([[1,2,3],[4,5,6]])
print(x[1][2])

tensor(6)


In [4]:
x[0][1] = 8
print(x)

tensor([[1, 8, 3],
        [4, 5, 6]])


In [5]:
x = torch.tensor([[1]])
x

tensor([[1]])

In [6]:
x = torch.tensor(2.5)
x

tensor(2.5000)

In [7]:
# We use item to get a pyton number from a tensor containing a single value
x.item()

2.5

In [8]:
x = torch.tensor([[1., -1.], [1., 1.]], requires_grad=True)
out = x.pow(2).sum()
out.backward()
x.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

In [9]:
a = torch.randn(4)

torch.add(a,20)

tensor([20.1514, 20.1320, 19.6723, 19.6819])

In [10]:
b = torch.randn(4)
c = torch.randn(4,1)
c

tensor([[-0.8567],
        [ 1.1518],
        [ 0.6752],
        [-1.5781]])

In [11]:
torch.add(b,c,alpha = 10)

tensor([[ -8.5254,  -9.5826,  -9.6658,  -9.0749],
        [ 11.5593,  10.5022,  10.4190,  11.0099],
        [  6.7931,   5.7360,   5.6528,   6.2437],
        [-15.7395, -16.7966, -16.8798, -16.2889]])

In [12]:
# Okay so the output is a - (b * alpha) to get the answer why?
# So the alpha parameter is optional got it perhaps it is a scalar.
a = torch.tensor((1, 2))
b = torch.tensor((0, 1))
torch.sub(a, b,alpha = 1)

tensor([1, 1])

### 2. Create a random tensor with shape `(7, 7)`.


In [13]:
# Here we create a random tensor with shape 7.7

In [14]:
# Import torch
import torch

# Create random tensor
x = torch.rand(7,7)
x

tensor([[0.7895, 0.4081, 0.0841, 0.1076, 0.8212, 0.1510, 0.2483],
        [0.4827, 0.3308, 0.3287, 0.1493, 0.2698, 0.3783, 0.1702],
        [0.5499, 0.8624, 0.6513, 0.8026, 0.8564, 0.8359, 0.4027],
        [0.6124, 0.2463, 0.6451, 0.0473, 0.9293, 0.9593, 0.9717],
        [0.4578, 0.4637, 0.5485, 0.1013, 0.7583, 0.6894, 0.5559],
        [0.0344, 0.9488, 0.1178, 0.9435, 0.2102, 0.1978, 0.2115],
        [0.4598, 0.5755, 0.8236, 0.2314, 0.2055, 0.3413, 0.2852]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [15]:
# Create another random tensor
b = torch.rand(1,7)

# Perform matrix multiplication, use the matmul arguement not mul argument
product = torch.matmul(x,b.T)

# Performed Transpose on B so we can matrix multiply we have to align the inner dimensions in
# order for it to work
product, b.T.shape

(tensor([[1.8929],
         [1.4993],
         [3.5258],
         [2.7250],
         [2.3187],
         [2.1216],
         [1.9445]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [16]:
# Set manual seed
seed = 42
torch.manual_seed(seed)

# Create two random tensors
random_tensor_a = torch.rand(2,2)
random_tensor_b = torch.rand(2,2)

# Matrix multiply tensors
product2 = torch.matmul(random_tensor_a,random_tensor_b)
product2

tensor([[0.5792, 1.2563],
        [0.3956, 0.9914]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [17]:
# Set random seed on the GPU so GPU equivalent is torch.cuda.manual_seed(1234)
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [29]:
# Set random seed
torch.cuda.manual_seed(42)

# Check for access to GPU set runtime to t4 GPU
device = "cuda" if torch.cuda.is_available else "cpu"
device
# Create two random tensors on GPU
tensor_a_gpu = torch.rand(2,3,device = device)
tensor_b_gpu = torch.rand(2,3,device = device)

print(tensor_a_gpu),print(tensor_b_gpu)

tensor([[0.6130, 0.0101, 0.3984],
        [0.0403, 0.1563, 0.4825]], device='cuda:0')
tensor([[0.9877, 0.1289, 0.5621],
        [0.5221, 0.7445, 0.5955]], device='cuda:0')


(None, None)


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [31]:
# Perform matmul on tensor_A and tensor_B
product_gpu = torch.matmul(tensor_a_gpu,tensor_b_gpu.T)
print(product_gpu)

tensor([[0.8307, 0.5648],
        [0.3312, 0.4247]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [38]:
# Find max
torch.max(product_gpu)
# Find min
torch.min(product_gpu)

print(torch.max(product_gpu)),print(torch.min(product_gpu))

tensor(0.8307, device='cuda:0')
tensor(0.3312, device='cuda:0')


(None, None)

### 9. Find the maximum and minimum index values of the output of 7.

Argmin gives the maximum index value while argmin gives the minimum index value

In [40]:
# Find arg max
torch.argmax(product_gpu)

# Find arg min
torch.argmin(product_gpu)

print(torch.argmax(product_gpu)), print(torch.argmin(product_gpu))

tensor(0, device='cuda:0')
tensor(2, device='cuda:0')


(None, None)


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [44]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor_c = torch.rand(1,1,1,10)

# Remove single dimensions
y = torch.squeeze(random_tensor_c)

# Print out tensors and their shapes
print(random_tensor_c), print(random_tensor_c.shape), print(y),print(y.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])


(None, None, None, None)

In [42]:
# Recall that if u want 1 you have to count from o
random_tensor_c

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])